import React, { useState } from "react";

const BACKEND_URL =
  import.meta.env.VITE_BACKEND_URL ||
  "https://debugsense-ai-xoft.onrender.com";

function App() {
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [language, setLanguage] = useState("JavaScript");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [systemMessage, setSystemMessage] = useState("");

  const analyzeError = async () => {
    if (!code.trim()) {
      setSystemMessage("Please enter your code.");
      return;
    }

    if (!error.trim()) {
      setSystemMessage("Please enter the error message.");
      return;
    }

    setLoading(true);
    setResult(null);
    setSystemMessage("");

    try {
      const apiUrl = `${BACKEND_URL.replace(/\/$/, "")}/api/debug`;

      console.log("Sending request to:", apiUrl);

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          code: code,
          error: error,
          language: language,
        }),
      });

      const data = await response.json();

      console.log("Backend response:", data);

      if (!response.ok) {
        throw new Error(
          data.message || `Backend returned ${response.status}`
        );
      }

      if (!data.success) {
        throw new Error(data.message || "Unable to analyze the code.");
      }

      setResult(data.result);
    } catch (err) {
      console.error("DebugSense AI Error:", err);

      setSystemMessage(
        err.message || "Unable to connect to the backend."
      );
    } finally {
      setLoading(false);
    }
  };

  const clearAll = () => {
    setCode("");
    setError("");
    setResult(null);
    setSystemMessage("");
  };

  return (
    <div className="app">
      <header className="header">
        <div>
          <h1>DebugSense AI</h1>
          <p>AI-powered code debugging assistant</p>
        </div>

        <div className="status">
          <span className="status-dot"></span>
          Backend Connected
        </div>
      </header>

      <main className="container">
        {/* CODE SECTION */}
        <section className="card">
          <div className="section-header">
            <div className="number">01</div>

            <div>
              <h2>CODE INPUT</h2>
              <p>Paste the code that is causing the problem.</p>
            </div>

            <div className="required">REQUIRED</div>
          </div>

          <div className="field">
            <label>PROGRAMMING LANGUAGE</label>

            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
            >
              <option>JavaScript</option>
              <option>Python</option>
              <option>Java</option>
              <option>C</option>
              <option>C++</option>
              <option>C#</option>
              <option>PHP</option>
              <option>TypeScript</option>
            </select>
          </div>

          <div className="field">
            <label>YOUR CODE</label>

            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder={`Example:

const users = undefined;

users.map(user => user);`}
              rows={12}
            />
          </div>
        </section>

        {/* ERROR SECTION */}
        <section className="card">
          <div className="section-header">
            <div className="number">02</div>

            <div>
              <h2>ERROR INFORMATION</h2>
              <p>Paste the error message generated by your program.</p>
            </div>

            <div className="required">REQUIRED</div>
          </div>

          <div className="field">
            <label>ERROR MESSAGE</label>

            <textarea
              value={error}
              onChange={(e) => setError(e.target.value)}
              placeholder="Example: TypeError: Cannot read properties of undefined (reading 'map')"
              rows={6}
            />
          </div>
        </section>

        {/* SYSTEM MESSAGE */}
        {systemMessage && (
          <div className="system-message">
            <div className="message-title">⚠ SYSTEM MESSAGE</div>
            <div className="message-text">{systemMessage}</div>
          </div>
        )}

        {/* RESULT */}
        {result && (
          <section className="result-card">
            <div className="result-header">
              <div className="number">03</div>

              <div>
                <h2>AI ANALYSIS</h2>
                <p>Debugging analysis from DebugSense AI.</p>
              </div>
            </div>

            <div className="result-content">
              {typeof result === "string" ? (
                <pre>{result}</pre>
              ) : (
                <pre>{JSON.stringify(result, null, 2)}</pre>
              )}
            </div>
          </section>
        )}

        {/* BUTTONS */}
        <div className="actions">
          <button
            className="clear-button"
            onClick={clearAll}
            disabled={loading}
          >
            CLEAR
          </button>

          <button
            className="analyze-button"
            onClick={analyzeError}
            disabled={loading}
          >
            {loading ? "ANALYZING..." : "✦ ANALYZE ERROR"}
          </button>
        </div>
      </main>
    </div>
  );
}

export default App;